### ISSUE TITLE
Elasticsearch

### ISSUE THREAD

**Issue by Leadersheepy** [Leadersheepy/H3_microservice#1]
### Problème 

J'essaye depuis ce matin de commencer le projet en installant elasticsearch, mais dès que le conteneur se lance/start sur mon pc, mon ordinateur freeze et cela fait crash visual studio code aussi. 

Quelles sont les solutions possibles ? (Sachant que je n'ai pas d'autre ordinateur, enfin, j'ai celui de mon travail, mais il a déjà du mal avec docker desktop installé dessus + il n'est pas sur Ubuntu)

**Comment by bdallard** [comment]
Hello il faut que tu diminue ce paramètre `ES_JAVA_OPTS=-Xms512m -Xmx512m` passe le a 128m

**Comment by bdallard** [comment]
Btw dans ton docker-compose.yml file tu as 3 noeud élastique diminue fait en juste un seul ca sera mieux

**Comment by bdallard** [comment]
Tu peux aussi aller dans les paramètres de configuration docker et voir si il a +4Gb de RAM (donne lui le plus possible)
